from pathlib import Path
import os

ROOT_DIR = Path(__file__).resolve().parents[1]
DB_PATH = Path(os.getenv("DB_PATH", str(ROOT_DIR / "database" / "app.db")))
SCHEMA_PATH = ROOT_DIR / "database" / "schema.sql"

DEFAULT_BOARD_SIZE = 15
DEFAULT_WIN_LENGTH = 5
MAX_BOARD_SIZE = 99
DEFAULT_MULTI_PLAYERS = 4
MIN_MULTI_PLAYERS = 2
MAX_MULTI_PLAYERS = 4

ELO_NEW_PLAYER_GAMES = 30
ELO_ESTABLISHED_GAMES = 100
ELO_K_NEW = 40
ELO_K_ESTABLISHED = 24
ELO_K_VETERAN = 16

CHAT_BANNED_WORDS = (
	"dm",
	"dit",
	"deo",
	"vl",
	"vcl",
	"ngu",
	"lon",
	"cc",
)
CHAT_SPAM_WINDOW_SECONDS = 8
CHAT_SPAM_MAX_MESSAGES = 5

RANK_QUEUE_WINDOW_SECONDS = 60
RANK_QUEUE_MAX_JOINS_PER_USER = 8
RANK_QUEUE_MAX_JOINS_PER_IP = 20
RANK_QUEUE_MAX_DISTINCT_USERS_PER_IP = 2

ADMIN_DASHBOARD_TOKEN = os.getenv("ADMIN_DASHBOARD_TOKEN", "admin-dev-token")
